---
- name: installing and launching metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: install metricbeat deb
    command: sudo dpkg -i metricbeat-7.4.0-amd64.deb

  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module
    command: sudo metricbeat modules enable docker

  - name: setup Metricbeat
    command: sudo metricbeat setup

  - name: start Metricbeat service
    command: sudo service metricbeat start

  - name: enable service Metricbeat on boot
    command: sudo systemctl enable metricbeat

 # Use command module
  - name: Increase virtual memory
    command: sysctl -w vm.max_map_count=262144

    # Use shell module
  - name: Increase virtual memory on restart
    shell: echo "vm.max_map_count=262144" >> /etc/sysctl.